name: Build

on: push

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: meza-ubuntu-slim
    steps:
      - name: "⬇️ Checkout"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Semantic Release
        id: get-next-version
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          dry_run: true
          extra_plugins: |
            conventional-changelog-conventionalcommits 
            @semantic-release/github 
            @semantic-release/changelog 
            semantic-release-export-data

      - name: "Package and Publish"
        if: ${{ steps.get-next-version.outputs.new_release_published == 'true'  }}
        run: cd src && zip -r ../MezacraftS3-${{ steps.get-next-version.outputs.new_release_version }}.zip *
      - name: "Save SHA1 hash of the file"
        if: ${{ steps.get-next-version.outputs.new_release_published == 'true'  }}
        run: |
          SHA="$(sha1sum MezacraftS3-${{ steps.get-next-version.outputs.new_release_version }}.zip | cut -d ' ' -f 1)"
          echo $SHA > "MezacraftS3-${{ steps.get-next-version.outputs.new_release_version }}.zip.sha1"
          echo $SHA >> $GITHUB_STEP_SUMMARY
      - name: Semantic Release
        if: ${{ steps.get-next-version.outputs.new_release_published == 'true'  }}
        id: release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits 
            @semantic-release/github 
            @semantic-release/changelog 
            semantic-release-export-data
      - uses: wolfigster/rcon-action@db73f3f321ec75d5d165f2bdfa0ce08b1622d431 # v1.0.2
        if: ${{ steps.get-next-version.outputs.new_release_published == 'true'  }}
        with:
          server: 'minecraft.meza.gg'
          port: '25575'
          password: ${{ secrets.RCON_PASSWORD }}
          commands: '["pack set \"https://github.com/meza/MezacraftS3-resource-pack/releases/download/v${{ steps.get-next-version.outputs.new_release_version }}/MezacraftS3-${{ steps.get-next-version.outputs.new_release_version }}.zip\""]'
